/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import App.DBConnection;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ahmad Dimyati
 */
public class Form extends javax.swing.JFrame {
    int xx, xy, jam = 1;
    DBConnection dbConnection = new DBConnection();
    private static Integer jenisSelected = 0;
    double total, hargaTotal;
    
    // set variable untuk get value jenis
    private static Integer getJenisSelected() {
        return jenisSelected;
    }
    
    // set harga
    private void setHarga() {
        jam = Integer.parseInt(fieldJam.getText());
        
        total = switch (jenisSelected) {
            case 1 -> 3000;
            case 2 -> 5000;
            case 3 -> 8000;
            case 4 -> 10000;
            default -> 0;
        };
        
        if (jam >= 5) {
            total = total / 2;
        }
        
        hargaTotal = total * jam;

        lblTotal.setText("TOTAL : " + String.format("Rp.%,.0f", hargaTotal));
    }
    
    // cek jika bukan nomot
    private static boolean isNotNumber(String str) {
        try {
            
            Integer.parseInt(str);

            // If parsing succeeds, it's a number
            return false;
        } catch (NumberFormatException e) {
            // If an exception is caught, it's not a number
            return true;
        }
    }
    
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldJenis = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldKartuIdentitas = new javax.swing.JTextField();
        fieldNoTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldAlamat = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldKeterangan = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        fieldJam = new javax.swing.JTextField();
        fieldTanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM RENTAL PS");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(236, 243, 243));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 88, 111));
        jLabel1.setText("FORM RENTAL");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 180, 170));
        jLabel2.setText("KODE RENTAL :");

        fieldKode.setBackground(new java.awt.Color(0, 88, 111));
        fieldKode.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldKode.setForeground(new java.awt.Color(255, 255, 255));
        fieldKode.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 180, 170));
        jLabel3.setText("JENIS :");

        fieldJenis.setBackground(new java.awt.Color(0, 88, 111));
        fieldJenis.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldJenis.setForeground(new java.awt.Color(255, 255, 255));
        fieldJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "PS 2 (Rp. 3.000 / Per Jam)", "PS 3 (Rp. 5.000 / Per Jam)", "PS 4 (Rp. 8.000 / Per Jam)", "PS 5 (Rp. 10.000 / Per Jam)" }));
        fieldJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldJenisMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 180, 170));
        jLabel4.setText("NAMA PENYEWA :");

        fieldNama.setBackground(new java.awt.Color(0, 88, 111));
        fieldNama.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldNama.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 180, 170));
        jLabel5.setText("KARTU IDENTITAS :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 180, 170));
        jLabel7.setText("NO. TELEPON / HP :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 180, 170));
        jLabel8.setText("ALAMAT :");

        fieldKartuIdentitas.setBackground(new java.awt.Color(0, 88, 111));
        fieldKartuIdentitas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldKartuIdentitas.setForeground(new java.awt.Color(255, 255, 255));

        fieldNoTelepon.setBackground(new java.awt.Color(0, 88, 111));
        fieldNoTelepon.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldNoTelepon.setForeground(new java.awt.Color(255, 255, 255));

        fieldAlamat.setBackground(new java.awt.Color(0, 88, 111));
        fieldAlamat.setColumns(20);
        fieldAlamat.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldAlamat.setForeground(new java.awt.Color(255, 255, 255));
        fieldAlamat.setRows(5);
        jScrollPane1.setViewportView(fieldAlamat);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 180, 170));
        jLabel9.setText("TANGGAL SEWA :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 180, 170));
        jLabel10.setText("JUMLAH JAM :");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 180, 170));
        jLabel11.setText("KETERANGAN :");

        fieldKeterangan.setBackground(new java.awt.Color(0, 88, 111));
        fieldKeterangan.setColumns(20);
        fieldKeterangan.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        fieldKeterangan.setRows(5);
        jScrollPane2.setViewportView(fieldKeterangan);

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 88, 111));
        lblTotal.setText("TOTAL : RP. 0");

        btnSave.setBackground(new java.awt.Color(0, 180, 170));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 88, 111), 3));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 180, 170));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("BATAL");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 88, 111), 3));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        fieldJam.setBackground(new java.awt.Color(0, 88, 111));
        fieldJam.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldJam.setForeground(new java.awt.Color(255, 255, 255));
        fieldJam.setText("1");
        fieldJam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldJamKeyReleased(evt);
            }
        });

        fieldTanggal.setBackground(new java.awt.Color(0, 88, 111));
        fieldTanggal.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        fieldTanggal.setForeground(new java.awt.Color(255, 255, 255));
        fieldTanggal.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jika lebih dari 5 jam, maka harga akan di diskon sebesar 50%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldJam, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fieldNoTelepon, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldKartuIdentitas, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldJenis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldKode, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                            .addComponent(jSeparator1)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fieldJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldKartuIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fieldJam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // cek jenis
        if (jenisSelected == 0) {
            JOptionPane.showMessageDialog(null, "Jenis harus dipilih", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        // cek jika nama kosong
        if (fieldNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        // cek jika telepon kosong
        if (fieldNoTelepon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        // cek jika alamat
        if (fieldAlamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        // cek jika jam bukan angka
        if (isNotNumber(fieldJam.getText())) {
            JOptionPane.showMessageDialog(null, "Jam harus berupa angka", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        // cek jika jam kurang dari 1
        if (jam < 1) {
            JOptionPane.showMessageDialog(null, "Jam tidak boleh kurang dari 1", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        try {
            
            Connection conn = dbConnection.openConnection();
            PreparedStatement preparedStatement = conn.prepareStatement("INSERT INTO penyewa "
                    + "(kode, jenis, nama, kartu_identitas, telpon, alamat, jam, tanggal, total, keterangan, status, tanggal_pengembalian) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)");
            
            preparedStatement.setString(1, fieldKode.getText());
            preparedStatement.setInt(2, jenisSelected);
            preparedStatement.setString(3, fieldNama.getText());
            preparedStatement.setString(4, fieldKartuIdentitas.getText());
            preparedStatement.setString(5, fieldNoTelepon.getText());
            preparedStatement.setString(6, fieldAlamat.getText());
            preparedStatement.setInt(7, jam);
            preparedStatement.setString(8, fieldTanggal.getText());
            preparedStatement.setDouble(9, hargaTotal);
            preparedStatement.setString(10, fieldKeterangan.getText());
            preparedStatement.setString(11, null);
            
            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan", "Info", JOptionPane.INFORMATION_MESSAGE);
                new List().show();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal ditambahkan", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new Welcome().show();
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // get date
        LocalDateTime currentDateTime = LocalDateTime.now();
        
        // set value field kode
        String kodeRental = "RENT-";
        kodeRental += currentDateTime.format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss-"));
        
        try {
            
            Connection conn = dbConnection.openConnection();
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) AS recordCount FROM penyewa");
            if (resultSet.next()) {
                kodeRental += resultSet.getInt("recordCount") + 1;
            }
            
            dbConnection.closeConnection();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fieldKode.setText(kodeRental);
        
        // set value field tanggal
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = currentDateTime.format(formatter);
        fieldTanggal.setText(formattedDateTime);
    }//GEN-LAST:event_formComponentShown

    private void fieldJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldJenisMouseClicked
        fieldJenis.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the selected item from the JComboBox
                jenisSelected = (int) fieldJenis.getSelectedIndex();
                
                setHarga();
            }
        });
    }//GEN-LAST:event_fieldJenisMouseClicked

    private void fieldJamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJamKeyReleased
        // cek jenis
        if (jenisSelected == 0) {
            JOptionPane.showMessageDialog(null, "Jenis harus dipilih", "Perhatian", JOptionPane.WARNING_MESSAGE);
        }
        
        if (fieldJam.getText().trim().isEmpty()) {
            fieldJam.setText("1");
        }
        
        setHarga();
    }//GEN-LAST:event_fieldJamKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextArea fieldAlamat;
    private javax.swing.JTextField fieldJam;
    private javax.swing.JComboBox<String> fieldJenis;
    private javax.swing.JTextField fieldKartuIdentitas;
    private javax.swing.JTextArea fieldKeterangan;
    private javax.swing.JTextField fieldKode;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNoTelepon;
    private javax.swing.JTextField fieldTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
